export const businessSubSectorConst = [
  'Soybean Farming',
  'Oilseed (except Soybean) Farming',
  'Oilseed (except Soybean) Farming ',
  'Dry Pea and Bean Farming',
  'Dry Pea and Bean Farming ',
  'Wheat Farming',
  'Wheat Farming',
  'Corn Farming',
  'Corn Farming ',
  'Rice Farming',
  'Rice Farming',
  'Other Grain Farming',
  'Oilseed and Grain Combination Farming ',
  'All Other Grain Farming ',
  'Vegetable and Melon Farming',
  'Potato Farming ',
  'Other Vegetable (except Potato) and Melon Farming ',
  'Orange Groves',
  'Orange Groves',
  'Citrus (except Orange) Groves',
  'Citrus (except Orange) Groves ',
  'Noncitrus Fruit and Tree Nut Farming',
  'Apple Orchards ',
  'Grape Vineyards ',
  'Strawberry Farming ',
  'Berry (except Strawberry) Farming ',
  'Tree Nut Farming ',
  'Fruit and Tree Nut Combination Farming ',
  'Other Noncitrus Fruit Farming ',
  'Food Crops Grown Under Cover',
  'Mushroom Production ',
  'Other Food Crops Grown Under Cover ',
  'Nursery and Floriculture Production',
  'Nursery and Tree Production ',
  'Floriculture Production ',
  '11191 TobaccoFarming',
  '111910 TobaccoFarming',
  'Cotton Farming',
  'Cotton Farming',
  'Sugarcane Farming',
  'Sugarcane Farming',
  'Hay Farming',
  'Hay Farming ',
  'All Other Crop Farming',
  'Sugar Beet Farming ',
  'Peanut Farming ',
  'All Other Miscellaneous Crop Farming ',
  'Beef Cattle Ranching and Farming, including Feedlots',
  'Beef Cattle Ranching and Farming ',
  'Cattle Feedlots ',
  'Dairy Cattle and Milk Production',
  'Dairy Cattle and Milk Production',
  'Dual-Purpose Cattle Ranching and Farming',
  'Dual-Purpose Cattle Ranching and Farming ',
  '11221 Hogand Pig Farming',
  '112210 Hogand Pig Farming',
  'Chicken Egg Production',
  'Chicken Egg Production ',
  'Broilers and Other Meat Type Chicken Production',
  'Broilers and Other Meat Type Chicken Production ',
  'Turkey Production',
  'Turkey Production',
  'Poultry Hatcheries',
  'Poultry Hatcheries',
  'Other Poultry Production',
  'Other Poultry Production ',
  'Sheep Farming',
  'Sheep Farming',
  'Goat Farming',
  'Goat Farming',
  'Aquaculture',
  'Finfish Farming and Fish Hatcheries ',
  'Shellfish Farming ',
];
