export const businessSectorConst = [
  'Crop Production',
  'Oilseed and Grain Farming ',
  'Vegetable and Melon Farming',
  'Fruit and Tree Nut Farming',
  'Greenhouse, Nursery, and Floriculture Production',
  'Other Crop Farming',
  'Animal Production and Aquaculture',
  'Cattle Ranching and Farming',
  'Hog and Pig Farming',
  'Poultry and Egg Production',
  'Sheep and Goat Farming',
  'Aquaculture',
  'Other Animal Production',
  'Forestry and Logging',
  'Timber Tract Operations',
  'Forest Nurseries and Gathering of Forest Products',
  'Logging',
  'Fishing, Hunting and Trapping',
  'Fishing',
  'Hunting and TrappingT:',
  'Support Activities for Agriculture and Forestry',
  'Support Activities for Crop Production',
  'Support Activities for Animal Production',
  'Support Activities for Forestry',
  'Oil and Gas Extraction',
  'Oil and Gas Extraction',
  'Mining (except Oil and Gas)',
  'Coal Mining',
  'Metal Ore Mining',
];
